name: Deploy

on:
  push: 
    branches:
      - master
  workflow_dispatch:

jobs: 
  deploy: 
    name: "Deploy to AWS EC2 Virtual Machine"
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
    run: |
      mkdir -p ~/.ssh/
      echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
      chmod 600 ~/.ssh/deploy-key.pem
      cat >>~/.ssh/config <<END
      Host my-vm
        HostName $SSH_IP
        User $SSH_USER
        IdentityFile ~/.ssh/deploy-key.pem
        StrictHostKeyChecking no
      END
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_IP: ${{ secrets.SSH_IP }}

    - name: Print project root directory
      run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && pwd'
